// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_lizaohG5fWy2pZdSUInnfX5ur6_PFzU',
    appId: '1:42503801369:web:71fae2a55588c39e283888',
    messagingSenderId: '42503801369',
    projectId: 'fir-app-dec80',
    authDomain: 'fir-app-dec80.firebaseapp.com',
    storageBucket: 'fir-app-dec80.appspot.com',
    measurementId: 'G-47WGWLGCGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT9PovBpIlyYTSahUlIrxlW4XH0cPp3V8',
    appId: '1:42503801369:android:797f2a86a931bb1d283888',
    messagingSenderId: '42503801369',
    projectId: 'fir-app-dec80',
    storageBucket: 'fir-app-dec80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8X9mQ0o0EPOK8y8D5lD3fRTcyoYZ61io',
    appId: '1:42503801369:ios:0862ffcdbb6e47cd283888',
    messagingSenderId: '42503801369',
    projectId: 'fir-app-dec80',
    storageBucket: 'fir-app-dec80.appspot.com',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8X9mQ0o0EPOK8y8D5lD3fRTcyoYZ61io',
    appId: '1:42503801369:ios:d15f99e158bbfbd1283888',
    messagingSenderId: '42503801369',
    projectId: 'fir-app-dec80',
    storageBucket: 'fir-app-dec80.appspot.com',
    iosBundleId: 'com.example.firebaseapp.RunnerTests',
  );
}
